server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb+srv://joffre:joffre@bootcamp-microservicios.c9yhl.mongodb.net/activo-personal?retryWrites=true&w=majority

    